server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      mvc:
        routes:
          - id: api-a
            uri: http://localhost:8081
            predicates:
              - Path=/a/**

          - id: api-b
            uri: http://localhost:8082
            predicates:
              - Path=/b/**

          - id: api-c
            uri: http://localhost:8083
            predicates:
              - Path=/c/**
